spring.application.name=product
spring.datasource.url=jdbc:mysql://localhost:3306/pwb_db
spring.datasource.username=${DB_USERNAME:user_db}
spring.datasource.password=${DB_PASSWORD:GallitoVazquez2007?}
spring.datasource.driverClassName=com.mysql.jdbc.Driver

#Para crear la tabla automaticamente con hibernate
spring.jpa.hibernate.ddl-auto=update

# Files
app.upload.dir=uploads
app.upload.images=img
